version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "4000:4000"
      - "3000:3000"
    links:
      - mongodb
#      - conda
    environment:
      - NODE_ENV=production
#  conda:
#    image: continuumio/anaconda3
